# Changes here will be overwritten by Copier
_commit: v0.13.0
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.jermiahjoseph@gmail.com
author_full_name: Jermiah Joseph
github_username: jjjermiah
has_additional_authors: false
project_description: Test 1 is the first test project
project_name: Test1
project_slug: test1
publish_to_github: true
python_version: '3.12'
repo_location: jjjermiah
